# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/realmayus/youmatter/issues"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false
license="MIT License"

[[mods]]
  modId="youmatter"
  version="${version}"
  displayName="YouMatter"
  displayURL="https://minecraftforge.net"
  credits="I'd like to thank my mother and father."
  authors="Author"
  description='''
  Lets you craft dirt into diamonds. This is a traditional mod that has existed for eons. It is ancient. The holy Notch created it. Jeb rainbowfied it. Dinnerbone made it upside down. Etc.
  '''

  [[dependencies.youmatter]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.youmatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"